### PR TITLE
Drop Python 2.7 and 3.5 support. Upgrade codebase

### PR DESCRIPTION
**Pull request by kleschenko**
### CHANGES
Python 2.7 is not supported anymore and Celery dropped its support in the 5.0 release. Also, Python 3.5 is reaching EOL at the end of September. This PR removes Python 2.7 and 3.5 support and upgrades codebase to use Python3-only syntax

* Used `pyupgrade` tool to upgrade codebase to the Python3.6+ syntax
* Used `isort` to sort imports
* Updated list of supported versions

### CODE REVIEW

**Comment by sibson** [comment]
This is a rather large PR and on a quick look it's unclear how it semantically differs from #178.

**Comment by kleschenko** [comment]
@sibson updated PR description to outline the list of changes. After rebase on the latest master this PR contains only changes related to the syntax-upgrade to the Python 3.6+. We'll need to have a major version bump if you'll decide to proceed with this change.

**Comment by sibson** [comment]
@kleschenko great thanks for the update and noting the need for a version upgrade, that was going to be my next question.  I'll try to push a final release out before merging this change and bumping to the next major.

**Review by auvipy — APPROVED** [review]

**Comment by sibson** [comment]
thanks, ✨ 🍰 ✨

**Pull request merged**
