### PR TITLE
Support for Celery 5 (RC)

### PR DESCRIPTION
**Pull request by noamkush**
This adds celery 5 RC to tox config and fixes compatibility (`celery.five` removed). Also removed `simplejson` shim.

### CODE REVIEW

**Comment by sibson** [comment]
Tests are failing, likely for unrelated reasons.  Would like to see green tests before I merge.

**Comment by noamkush** [comment]
Yeah, #176 fixes the tests. I can rebase after you merge it.

**Comment by sibson** [comment]
thanks, I'd missed that PR.

**Comment by noamkush** [comment]
@sibson, tests are now passing.

**Pull request merged**
