### PR TITLE
Retry the initial redis connect attempt

### PR DESCRIPTION
**Pull request by HoverHell**
Similar to what the default beat scheduler does

### CODE REVIEW

**Comment by HoverHell** [comment]
Also related: https://github.com/wegift/redbeat/commit/fe9da71392a7c017af40d7408b3eec48f11a4e87

**Comment by sibson** [comment]
I'm planning on merging #80, does that make this change unnecessary? or is there still a need for this?

**Comment by HoverHell** [comment]
> #80, does that make this change unnecessary?

Likely; the simple test is to start redbeat when redis is not running.

I made this patch despite #80 to handle this situation as close to default celerybeat as possible.

**Comment by sibson** [comment]
@HoverHell this has conflicts.  Could you update or close as appropriate?

**Comment by sibson** [comment]
@HoverHell should I be looking to merge this PR or is it obsoleted by #80?

**Comment by HoverHell** [comment]
Yes, it is likely obsoleted.

**Pull request closed without merging**
