### PR TITLE
redact password when logging redis url

### PR DESCRIPTION
**Pull request by sibson**
This change is [Reviewable](https://reviewable.io/reviews/sibson/redbeat/67)

### CODE REVIEW

**Comment by lambacck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[redbeat/schedulers.py, line 393 at r1](https://reviewable.io:443/reviews/sibson/redbeat/67#-KvXd_eUn4NcCwa6C4CE:-KvXd_eVb1--MmAnQSi-:bu23t6e) ([raw file](https://github.com/sibson/redbeat/blob/13b8e64c02d52a7ff66a2b51d5e3cfa5b9c0cbe9/redbeat/schedulers.py#L393)):*
> ```Python
>     @property
>     def info(self):
>         info = ['       . redis -> {}'.format(self.app.redbeat_conf.redis_url)]
> ```

This might not be the URL because it might not be the broker url and redbeat establishes it's own redis connection.

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sibson/redbeat/67)*

**Comment by lambacck** [comment]
I'm willing to accept on the grounds that it plugs the hole knowing that we'll need to find a different way to scrub the password.

---

Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sibson/redbeat/67#-:-KvXdnnkZN00qebd2TpT:bvan11l)*

**Comment by sigmavirus24** [comment]
:lgtm:

---

Review status: 0 of 1 files reviewed at latest revision, 2 unresolved discussions.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sibson/redbeat/67#-:-KvXdWN9tniv0f_VPB-e:bnfp4nl)*

**Comment by lambacck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[redbeat/schedulers.py, line 393 at r1](https://reviewable.io:443/reviews/sibson/redbeat/67#-KvXd_eUn4NcCwa6C4CE:-KvXgH5V5tH729VeLcnM:bazdbw1) ([raw file](https://github.com/sibson/redbeat/blob/13b8e64c02d52a7ff66a2b51d5e3cfa5b9c0cbe9/redbeat/schedulers.py#L393)):*
<details><summary><i>Previously, lambacck (Christopher Lambacher) wrote…</i></summary><blockquote>

This might not be the URL because it might not be the broker url and redbeat establishes it's own redis connection.
</blockquote></details>

```
import re
...

info = ['                      . redis -> {}'.format(re.sub(r'(redis://[^:]+:)([^@]+)(@)', '\1**\3', self.app.redbeat_conf.redis_url)]
```

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sibson/redbeat/67)*

**Comment by lambacck** [comment]
Review status: 0 of 1 files reviewed at latest revision, 1 unresolved discussion.

---

*[redbeat/schedulers.py, line 393 at r1](https://reviewable.io:443/reviews/sibson/redbeat/67#-KvXd_eUn4NcCwa6C4CE:-KvXhdAQHT2E1STTkW5v:bblkmnz) ([raw file](https://github.com/sibson/redbeat/blob/13b8e64c02d52a7ff66a2b51d5e3cfa5b9c0cbe9/redbeat/schedulers.py#L393)):*
> re.sub(r'(redis://[^:]+:)([^@]+)(@)', '\1**\3', 
re.sub(r'(redis://[^:]+:)([^@]+)(@)', r'\1**\3', 

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sibson/redbeat/67)*

**Comment by lambacck** [comment]
:+1:

---

Reviewed 1 of 1 files at r2.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sibson/redbeat/67#-:-KvXidsRpMdymLfFCQY6:bb6mt9b)*

**Comment by lambacck** [comment]
:lgtm:

---

Review status: all files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from [Reviewable](https://reviewable.io:443/reviews/sibson/redbeat/67#-:-KvXinZ19kt1-2r65u9w:bnfp4nl)*

**Comment by lambacck** [comment]
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[redbeat/schedulers.py, line 393 at r1](https://reviewable.io:443/reviews/sibson/redbeat/67#-KvXd_eUn4NcCwa6C4CE:-KvXirZLTz463kHAJumM:bjw1nd) ([raw file](https://github.com/sibson/redbeat/blob/13b8e64c02d52a7ff66a2b51d5e3cfa5b9c0cbe9/redbeat/schedulers.py#L393)):*
<details><summary><i>Previously, lambacck (Christopher Lambacher) wrote…</i></summary><blockquote>

> re.sub(r'(redis://[^:]+:)([^@]+)(@)', '\1**\3', 
re.sub(r'(redis://[^:]+:)([^@]+)(@)', r'\1**\3', 
</blockquote></details>

:LGTM:

---


*Comments from [Reviewable](https://reviewable.io:443/reviews/sibson/redbeat/67)*

**Pull request merged**
