### PR TITLE
Optimize next tick loading

### PR DESCRIPTION
**Pull request by sibson**
[Review on Reviewable](https://reviewable.io/reviews/sibson/redbeat/20)

### CODE REVIEW

**Comment by lambacck** [comment]
I'm not sure I understand why getting the schedule data in two chunks is beneficial.

---

Reviewed 1 of 3 files at r1.
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[redbeat/schedulers.py, line 219 \[r1\]](https://reviewable.io:443/reviews/sibson/redbeat/20#-KBxLDycTrY3fyWCc061:-KBxLDycTrY3fyWCc062:12255686) ([raw file](https://github.com/sibson/redbeat/blob/bf37f73879c549552ed7b1b0606d9cc824e628fd/redbeat/schedulers.py#L219)):*
why split this out if you are just going to join them again below?

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sibson/redbeat/20#-:-KBxN4W38gf9kPQSQw6C:335191304)*

**Comment by sibson** [comment]
Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---

*[redbeat/schedulers.py, line 219 \[r1\]](https://reviewable.io:443/reviews/sibson/redbeat/20#-KBxLDycTrY3fyWCc061:-KBxNN3H8yyIGJOaEcUP:913373997) ([raw file](https://github.com/sibson/redbeat/blob/bf37f73879c549552ed7b1b0606d9cc824e628fd/redbeat/schedulers.py#L219)):*
previously we fetched all ```tasks < now() + max_interval``` this change makes us get ```tasks < now() AND tasks > now() order by due limit 1```.  Thus we're not fetching all tasks in the (now(), now() + max_interval) range.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sibson/redbeat/20)*

**Comment by sibson** [comment]
we're fetching fewer tasks

---

Review status: 1 of 3 files reviewed at latest revision, 1 unresolved discussion.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sibson/redbeat/20#-:-KBxO3DJUnEu_beUdWe5:1856473620)*

**Comment by lambacck** [comment]
Reviewed 2 of 3 files at r1.
Review status: all files reviewed at latest revision, 1 unresolved discussion.

---

*[redbeat/schedulers.py, line 219 \[r1\]](https://reviewable.io:443/reviews/sibson/redbeat/20#-KBxLDycTrY3fyWCc061:-KBySW0aQ1KzYoJR2ZPt:-165743456) ([raw file](https://github.com/sibson/redbeat/blob/bf37f73879c549552ed7b1b0606d9cc824e628fd/redbeat/schedulers.py#L219)):*
I missed the num=1 thing. I got it now.

---


*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sibson/redbeat/20)*

**Comment by lambacck** [comment]
:+1:

---

Review status: :shipit: all files reviewed at latest revision, all discussions resolved, all commit checks successful.

---



*Comments from the [review on Reviewable.io](https://reviewable.io:443/reviews/sibson/redbeat/20#-:-KC1NDjPjzN4vHwaBNDX:676269983)*

**Pull request merged**
