### PR TITLE
Add sentinel support

### PR DESCRIPTION
**Pull request by arthurlogilab**
Use syntax for configuration used in https://github.com/dealertrack/celery-redis-sentinel

Related to #63

---
This change is [Reviewable](https://reviewable.io/reviews/sibson/redbeat/64)

### CODE REVIEW

**Comment by sibson** [comment]
This looks good, if you could include some docs explaining how to use the new options, I'll merge it. If you add tests I'll also be better able to ensure support doesn't become broken in future updates.

**Comment by arthurlogilab** [comment]
ok, thanks for the heads up. Will work on tests and docs next week.

**Comment by arthurlogilab** [comment]
@sibson done.

**Comment by sibson** [comment]
I'd like to see the tests passing before merging.  I think most of the failures are unrelated to your changes and I've put https://github.com/sibson/redbeat/pull/65 together to address them.

**Comment by sibson** [comment]
could you rebase to pickup the test fixes and then we should be good to merge.

**Comment by arthurlogilab** [comment]
sorry for the lag in fixing the tests

**Comment by sibson** [comment]
thanks, ✨ 🍰 ✨

**Comment by arthurlogilab** [comment]
@sibson thanks a bunch for merging this. Any ETA on a release of redbeat so we can stop pointing pip install to our fork ?

**Comment by sibson** [comment]
thanks for the nudge, 0.11.0 has been uploaded https://pypi.python.org/pypi/celery-redbeat/0.11.0

**Pull request merged**
