### PR TITLE
BeatLazyFunc-support for celery 4.4+

### PR DESCRIPTION
**Pull request by bigwolfdogroar**

### CODE REVIEW

**Comment by sibson** [comment]
Can you rebase to pick up the latest test suite?

**Comment by bigwolfdogroar** [comment]
Did i do it right?

**Comment by sibson** [comment]
Something looks like it went wrong, there are a lot of changes in here now.  I wonder if its because of the master->main rename.  The quickest solution might be to start a new branch from main, add your changes and start a new PR.  There might be other ways to get this fixed but you may end up spending more time figuring it out than doing what I suggested.

**Comment by bigwolfdogroar** [comment]
OK, I'll try to solve it.

**Pull request closed without merging**
