### PR TITLE
Add support for redis-py 3

### PR DESCRIPTION
**Pull request by noamkush**

### CODE REVIEW

**Comment by sibson** [comment]
Were you able to test this correctly works with both redis-py <3 and >=3?  The change seems fairly straight forward but changing the call args without having tests to cover the change is worrying me.

**Comment by noamkush** [comment]
Fakeredis supports redis-py>=3 so the test suite now passes with both <3 and >=3. The test suite does have coverage for these uses.

**Comment by sibson** [comment]
Great. I guess my question is should we update the tox.ini to ensure we run the tests with both versions of redis-py or is that not warranted?

**Comment by noamkush** [comment]
I'm against that since it makes it harder to drop this backward compatibility. It's just a python package which is not a painful upgrade.

**Comment by Rydra** [comment]
> I'm against that since it makes it harder to drop this backward compatibility. It's just a python package which is not a painful upgrade.

I think it's quite important. Kombu 4.4.0 requires redis-py >= 3.2.0 to work, otherwise raises a VersionMismatch exception. In order to keep up to date with this, redbeat should be updated to the last version of redis py.

**Comment by noamkush** [comment]
Fakeredis doesn't support redis-py 3.2 yet so the tests fail with 3.2 at the moment (see jamesls/fakeredis#235).

**Comment by orzarchi** [comment]
When is this change planned to go up on pipy?

**Pull request merged**
