### PR TITLE
fix OverflowError if timezone is positive

### PR DESCRIPTION
**Pull request by nikepan**
in this issue https://github.com/sibson/redbeat/issues/37 and PR changes fix only for negative offset. if offset is positive, error is present, because **maybe_make_aware/normalize** try to substract offset from min datetime

### CODE REVIEW

**Comment by sibson** [comment]
My understanding of this PR is if the TZ offset is > 0, we're ignoring the TZ offset. But in the case where it's < 0 we preserve the offset. Is that correct? If so I don't understand why this is the right solution.  In my mind either the offset is important and should be preserved or its not important and could be ignored is both cases.  

Would an acceptable alternative be, adding a day to avoid underflow and overflow?  There maybe another location where we need to make a similar change.

```
 self.schedule.is_due(self.last_run_at or datetime(MINYEAR, 1, 2, tzinfo=self.schedule.tz))
```

This is now the second time there has been an issue with this code, would it be possible to include a test case to help ensure regressions in future?

**Comment by nikepan** [comment]
thank you! making test in progress

**Comment by nikepan** [comment]
after writing the test, I found an error that leads to time discrepancies due to timezone. it feels right now.

**Comment by sibson** [comment]
I'm a little nervous about this change, because I've tried to fix a problem in this area code before and failed spectacularly.  Unfortunately, I can't recall the details to share or dismiss my fears.  I'm going to include this in the 2.0 release to mitigate the risk of this change.

**Pull request merged**
