### PR TITLE
Fix dev requirements

### PR DESCRIPTION
**Pull request by SpotlightKid**
Fix errors and warnings when running tests.

---
This change is [Reviewable](https://reviewable.io/reviews/sibson/redbeat/32)

### CODE REVIEW

**Comment by sibson** [comment]
I find the log info useful when debugging test failures, so I'm hesitant to remove capturelog without an alternative in place.

**Comment by SpotlightKid** [comment]
Here's the pytest-capturelog issue.

https://bitbucket.org/memedough/pytest-capturelog/issues/6/__multicall__-deprecated-in-upcoming

Maybe [pytest-catchlog](https://github.com/eisensheng/pytest-catchlog) is an alternative?

**Comment by sibson** [comment]
+1 to using catchlog

**Comment by SpotlightKid** [comment]
Do you want me to test catchlog and update the PR accordingly? I'm away for the weekend, so that won't be before Tuesday.

**Comment by sibson** [comment]
That would be great.  If I've time I'll do so myself.

**Comment by SpotlightKid** [comment]
I've rebased/updated the PR and replace capturelog with catchlog.

Here's a py.test call with catchlog installed without errors:

```
$ py.test tests/
========================================================== test session starts ==========================================================
platform linux -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
rootdir: /home/chris/work/celery/redbeat, inifile: 
plugins: catchlog-1.2.2, cov-2.3.1
collected 19 items 

tests/test_entry.py ..........
tests/test_json.py ......
tests/test_scheduler.py ..
tests/test_utils.py .

======================================================= 19 passed in 0.24 seconds =======================================================
```

And here's one with a test failure introduced in `test_entry.py` and a logging call inserted into `redbeat.RedBeatSchedulerEntry.save()`:

```
$ py.test -sv
========================================================== test session starts ==========================================================
platform linux -- Python 3.5.2, pytest-2.9.2, py-1.4.31, pluggy-0.3.1 -- /home/chris/lib/virtualenvs/celery/bin/python3.5
cachedir: .cache
rootdir: /home/chris/work/celery/redbeat, inifile: 
plugins: catchlog-1.2.2, cov-2.3.1
collected 19 items 

tests/test_entry.py::test_RedBeatEntry::test_basic_save FAILED
tests/test_entry.py::test_RedBeatEntry::test_delete PASSED
tests/test_entry.py::test_RedBeatEntry::test_due_at PASSED
tests/test_entry.py::test_RedBeatEntry::test_due_at_never_run PASSED
tests/test_entry.py::test_RedBeatEntry::test_due_at_overdue PASSED
tests/test_entry.py::test_RedBeatEntry::test_from_key_missing_meta PASSED
tests/test_entry.py::test_RedBeatEntry::test_from_key_nonexistent_key PASSED
tests/test_entry.py::test_RedBeatEntry::test_next PASSED
tests/test_entry.py::test_RedBeatEntry::test_next_only_update_last_run_at PASSED
tests/test_entry.py::test_RedBeatEntry::test_score PASSED
tests/test_json.py::RedBeatJSONEncoderTestCase::test_crontab PASSED
tests/test_json.py::RedBeatJSONEncoderTestCase::test_datetime PASSED
tests/test_json.py::RedBeatJSONEncoderTestCase::test_schedule PASSED
tests/test_json.py::RedBeatJSONDecoderTestCase::test_crontab PASSED
tests/test_json.py::RedBeatJSONDecoderTestCase::test_datetime PASSED
tests/test_json.py::RedBeatJSONDecoderTestCase::test_schedule PASSED
tests/test_scheduler.py::test_RedBeatScheduler::test_empty_schedule PASSED
tests/test_scheduler.py::test_RedBeatScheduler::test_schedule_includes_current_and_next PASSED
tests/test_utils.py::Test_utils::test_roundtrip PASSED

=============================================================== FAILURES ================================================================
___________________________________________________ test_RedBeatEntry.test_basic_save ___________________________________________________

self = <test_entry.test_RedBeatEntry testMethod=test_basic_save>

    def test_basic_save(self):
        e = self.create_entry()
        e.save()
    
        expected = {
            'name': 'testx',
            'task': 'tasks.test',
            'schedule': e.schedule,
            'args': None,
            'kwargs': None,
            'options': {},
            'enabled': True,
        }
        expected_key = (self.app.conf.REDBEAT_KEY_PREFIX + 'test').encode('utf-8')
    
        redis = self.app.redbeat_redis
        value = redis.hget(expected_key, 'definition').decode('utf8')
>       self.assertEqual(expected, json.loads(value, cls=RedBeatJSONDecoder))
E       AssertionError: {'arg[28 chars]t', 'name': 'testx', 'schedule': <freq: 1.00 m[50 chars]: {}} != {'arg[28 chars]t', 'schedule': <freq: 1.00 minute>, 'name': '[49 chars]: {}}
E         {'args': None,
E          'enabled': True,
E          'kwargs': None,
E       -  'name': 'testx',
E       ?               -
E       
E       +  'name': 'test',
E          'options': {},
E          'schedule': <freq: 1.00 minute>,
E          'task': 'tasks.test'}

tests/test_entry.py:30: AssertionError
----------------------------------------------------------- Captured log call -----------------------------------------------------------
schedulers.py              134 DEBUG    Stored entry: <Entry: test tasks.test() <freq: 1.00 minute>
================================================== 1 failed, 18 passed in 0.27 seconds ==================================================
```

**Comment by sibson** [comment]
great thanks ✨ 🍰 ✨

**Comment by SpotlightKid** [comment]
It seems like you need to manually uninstall pytest-capturelog in the CI environment or re-initialize the environment to fix the build.

**Comment by sibson** [comment]
good call; rebuild without cache seems to have done the trick.

**Pull request merged**
