### PR TITLE
upgrade to circleci 2.0

### PR DESCRIPTION
**Pull request by chdsbd**
Changes
- update to CircleCI 2.0. CircleCI 1.0 is EOL.
- fix `test_basic_save` expected value to match new redis return

### CODE REVIEW

**Comment by chdsbd** [comment]
@sibson I think this should be all set to merge. I think you need to go to https://travis-ci.org/account/repositories and enable Travis builds for this repo for them to run.

Also, I think there may be a race condition or something at https://github.com/chdsbd/redbeat/blob/master/tests/test_scheduler.py#L81-L82 because this failed with `3 != 2` for one test run, but the test passed after restarting the job.

**Comment by chdsbd** [comment]
@sibson This PR should be all set. Let me know if there is anything else I need to do before this is merged.

**Comment by sibson** [comment]
I'm not keen on supporting travis due to the recent takeover and layoffs.  I should have been more clear in the aforementioned commit, about my motivation.  I also didn't realize that circle 2.0 was going to be quite the bear to get setup that it appears to be.

I liked fakeredis because it allowed unit tests locally without mocking everything out. Replacing it with a real redis means the tests are now integration rather than unit and increases the effort required to run them the first time. I'd like to take a principled stand on unit over integration but am likely to be swayed by expediency.

It also seems that the latest redis has created a host of incompatibilities that has made it harder to support. It's clear that I need to take some time to sit down with this project and figure out how to best get it back into a healthy state, while I'll try to do this week.  I know there are a number of open PRs that address some aspect of the issues but like this one potentially introduce other issues.

**Comment by chdsbd** [comment]
@sibson Thanks for getting back to me.

Regarding Travis, I think it actually wouldn't be too difficult to move to CircleCI 2.0. Also, it seems like fakeredis [recently added py-redis 3.2 support](https://github.com/jamesls/fakeredis/issues/235#issuecomment-476160641), so I'll add that back.

I'll refactor this PR to move to CircleCI 2.0 and fix any broken tests.

**Comment by chdsbd** [comment]
@sibson Fixed

**Comment by sibson** [comment]
Great, thanks for all your effort on this and keeping going.  When I looked at the new circle stuff it wasn't immediately obvious what needed to happen.

**Pull request merged**
