### PR TITLE
BeatLazyFunc-support for celery4.4+

### PR DESCRIPTION
**Pull request by bigwolfdogroar**
I created a new branch from main and submitted the code.

### CODE REVIEW

**Comment by sibson** [comment]
I've two concerns here, first is the usage of pickle as a possible security issue and the second that this change is very invasive to the core dispatch loop.  I don't see similar code in upstream celery, so I am struggling to understand why it is needed here.  

The celery docs aren't really clear on the purpose of the LazyFunction but I suspect we don't need to shovel python code into Redis to make this work.  Part of the contract for broker/worker is they share code though shared source.

**Comment by bigwolfdogroar** [comment]
The purpose of the BeatLazyFunc is execute a func before send task to Redis. For example, I can get a timestamp in BeatLazyFunc instead of get timestamp in task.This timestamp can ensure the normal operation of the task when the worker cannot consume the task in time or needs to rerun the historical task data.
As for your concerns,
First, I need send a function object in json schedule to Redis. I didn't find other method to archive it.
Second, I refer the code in  upstream celery. [Row 383 in celery/beat](https://github.com/celery/celery/blob/master/celery/beat.py)

This just the way that i solved this problem in my project.

**Comment by sibson** [comment]
The two lines related to LazyFunc around 383, seem reasonable to include but the other changes create a security risk and are too invasive for me to merge.  I thought the earlier version of the PR didn't have as many changes to the core loop.  Celery itself does a string to function lookup that avoids round-tripping code though external stores.  If you follow that model I think we could include this feature.

**Comment by sibson** [comment]
Closing, no updates in over a year and currently conflicts with main.

**Pull request closed without merging**
